### ISSUE TITLE
Error 500 undefined method `collect' for nil:NilClass

### ISSUE THREAD

**Issue by sytkosa** [nodecarter/redmine_custom_reports#44]
Error
undefined method `collect' for nil:NilClass 

Redmine
![image](https://user-images.githubusercontent.com/10109949/46625111-5c7cec80-cb3b-11e8-8a6e-2d972bc48f3c.png)

Log

 /var/www/redmine/plugins/redmine_custom_reports/app/helpers/custom_reports_helper.rb:7:in `operators_for_select'
/var/www/redmine/plugins/redmine_custom_reports/app/views/custom_reports/_series_filters.html.erb:32:in `block in _ed456a125b1fcfe17c1ed4be48ee585d'
/var/www/redmine/plugins/redmine_custom_reports/app/views/custom_reports/_series_filters.html.erb:7:in `each'

version 0.1.5

**Comment by KedXP** [comment]
Hello!
Have the same error.
```

Completed 500 Internal Server Error in 475ms (ActiveRecord: 56.4ms)

ActionView::Template::Error (undefined method `collect' for nil:NilClass):
    29:                 class: 'hidden-for-sighted' %>
    30:               <%= select_tag "#{filter_attr}op[#{field}]",
    31:                 options_for_select(
    32:                   operators_for_select(options[:type]),
    33:                   query.operator_for(field)),
    34:                 id:    "operators_#{field_id}",
    35:                 class: 'toggle_series_filter_operator' %>
  plugins/redmine_custom_reports/app/helpers/custom_reports_helper.rb:7:in `operators_for_select'
  plugins/redmine_custom_reports/app/views/custom_reports/_series_filters.html.erb:32:in `block in _plugins_redmine_custom_reports_app_views_custom_reports__series_filters_html_erb___463200196316952335_69925161856920'
  plugins/redmine_custom_reports/app/views/custom_reports/_series_filters.html.erb:7:in `each'
  plugins/redmine_custom_reports/app/views/custom_reports/_series_filters.html.erb:7:in `_plugins_redmine_custom_reports_app_views_custom_reports__series_filters_html_erb___463200196316952335_69925161856920'
  plugins/redmine_custom_reports/app/views/custom_reports/_series.html.erb:8:in `_plugins_redmine_custom_reports_app_views_custom_reports__series_html_erb___220427591943874714_69925180595260'
  plugins/redmine_custom_reports/app/views/custom_reports/_form.html.erb:52:in `block (2 levels) in _plugins_redmine_custom_reports_app_views_custom_reports__form_html_erb___8841296710590182_69925181474280'
  plugins/redmine_custom_reports/app/views/custom_reports/_form.html.erb:51:in `block in _plugins_redmine_custom_reports_app_views_custom_reports__form_html_erb___8841296710590182_69925181474280'
  app/helpers/application_helper.rb:1190:in `labelled_form_for'
  plugins/redmine_custom_reports/app/views/custom_reports/_form.html.erb:5:in `_plugins_redmine_custom_reports_app_views_custom_reports__form_html_erb___8841296710590182_69925181474280'
  plugins/redmine_custom_reports/app/views/custom_reports/new.html.erb:3:in `_plugins_redmine_custom_reports_app_views_custom_reports_new_html_erb___4297969085119606702_69925181515960'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Redmine info:
```
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.8-p459 (2018-10-18) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.11.0
  Git                            2.19.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.2.8
  custom_menu                    1.7.2
  my_projects                    1.4
  redmine_agile                  1.4.6
  redmine_bootstrap_kit          0.2.3
  redmine_checklists             3.1.10
  redmine_ckeditor               1.1.4
  redmine_contacts               4.2.5
  redmine_contacts_helpdesk      4.1.0
  redmine_custom_reports         0.1.5
  redmine_image_clipboard_paste  3.3.0
  redmine_issue_tabs             1.1.1
  redmine_my_page                0.1.10
  redmine_people                 1.3.2
  redmineup_tags                 2.0.6
```

**Comment by federicoaaguirre** [comment]
Same here.! +1
